version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181"
    #ports:
    #  - "2181:2181"
  kafka:
    build: .
    ports:
      - "9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.1.101 #ipconfig getifaddr en
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

      #https://github.com/wurstmeister/kafka-docker
      #https://qiita.com/corhhey/items/f32821a254fa64cf88ab5f58832821

      
      #docker-compose stop
      #docker-compose rm
      #docker-compose up -d
      #docker-compose scale kafka=2
      #docker-compose ps -> 32825
      #./start-kafka-shell.sh 192.168.1.101 192.168.1.101:32825
      #opt/kafka/bin/kafka-topics.sh --create --topic topic --partitions 4 --replication-factor 1 --zookeeper 192.168.1.101:32825
      #opt/kafka/bin/kafka-topics.sh --describe --topic topic --zookeeper 192.168.1.101:32825
      #opt/kafka/bin/kafka-console-producer.sh --topic=topic --broker-list=`broker-list.sh`
      #opt/kafka/bin/kafka-console-consumer.sh --bootstrap-server 192.168.1.101:32825  --topic=topic --from-beginning
      #docker-compose stop

