#https://www.jianshu.com/p/a25c82bc5260
#docker run --name mywebapp -p 8080:8080 -d myapp

#docker build -t myapp .
#docker images
#docker run -it #{利用したいイメージ} /bin/bash
# entered container...
#java -jar mydockerapp.jar
#exit
#lsof -n -i4TCP:8080 | kill -9

FROM openjdk:8
MAINTAINER SatoshiAIKAWA
LABEL app="myApp" version="0.0.1" by="SatoshiAIKAWA"
COPY ./dockerdemo/build/libs/dockerdemo-0.0.1-SNAPSHOT.jar mydockerapp.jar
CMD java -jar mydockerapp.jar



